# primer programa
print('Diego Jacinto Deciga')
print('Barrio Buenavista S/N')
print('Santiago Tepatlaxco')
print('Naucalpan de Juarez')
print('cp 53216')
print('')
print('')
print('')
print('')
print('')
print('                                     Alvaro Godinez Rivero')
print('                                     cerrada acuducto obrage #8')
print('                                     San bartolito')
print('                                     Huxquilucan')